package entity;
// Generated 25.05.2015 15:34:14 by Hibernate Tools 4.3.1



/**
 * Recipeingredient generated by hbm2java
 */
public class Recipeingredient  implements java.io.Serializable {


     private Integer recipeIngredientId;
     private Ingredient ingredient;
     private Recipe recipe;
     private double quantity;
     private String unit;

    public Recipeingredient() {
    }

    public Recipeingredient(Ingredient ingredient, Recipe recipe, int quantity, String unit) {
       this.ingredient = ingredient;
       this.recipe = recipe;
       this.quantity = quantity;
       this.unit = unit;
    }
   
    public Integer getRecipeIngredientId() {
        return this.recipeIngredientId;
    }
    
    public void setRecipeIngredientId(Integer recipeIngredientId) {
        this.recipeIngredientId = recipeIngredientId;
    }
    public Ingredient getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }
    public Recipe getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }
    public double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }




}


